version: '3'
services:
  python:
    image: python
    build: 
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./code:/root/code 
      - ./data:/root/data
      - ./model:/root/model
      # - ./.vscode-server/root/.vscode-server
    